
site_name: Synthèses ingénieur civil
site_description: "Synthèses facile d'accès."
site_author: Aymco
site_url: https://aymco.github.io/public-obsidian
repo_name: aymco/public-obsidian
repo_url: https://github.com/Aymco/public-obsidian/
edit_uri: edit/main/docs/


extra_css:
  - stylesheets/extra.css

theme:
    name: 'material'
    custom_dir: overrides
    font:
        text: Lato
    icon:
      logo: material/lightbulb-on
    favicon: images/favicon.png
    language: fr
    features:
        - content.action.edit
        - navigation.tabs
        - navigation.indexes 
        #- navigation.instant
        #- navigation.top
        - search.suggest
        - search.highlight
        - toc.integrate 
    #- navigation.instant.progress
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: light theme

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: ayu theme

# Extensions
markdown_extensions:
  - mdx_math
  - footnotes
  - attr_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  #- pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks # for images
  - include_dir_to_nav:
      file_name_as_title: true
  - social:
      cards_layout: default/variant

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discordapp.com/channels/@me/404293091571531776/
      name: contact me on discord(aymco)
  analytics:
    provider: google
    property: G-EWC8Z1Z0D2
    feedback:
      title: Cela était utile ?
      ratings:
        - icon: material/emoticon-happy-outline
          name: c'était utile, merci !
          data: 1
          note: >-
            Merci pour le feedback !
        - icon: material/emoticon-sad-outline
          name: Cette page pourrait etre améliorée
          data: 0
          note: >- 
            Merci pour le feedback ! Aide à améliorer cette page en laissant un commentaire sur le github.

